### ISSUE TITLE
Provide ARM64 docker Images for Draco

### ISSUE THREAD

**Issue by jason-fox** [ging/fiware-draco#81]
Related to an open Apache NIFI ticket: https://issues.apache.org/jira/browse/NIFI-9177 

Once the upstream issue has been resolved, Draco should also be configured to create a working  arm64  image. I am currently getting the following error on start up on Apple Silicon M1 when running the Docker Image. (tested with `2.1.0` and earlier versions)

```
2021-08-29 04:36:48,799 WARN [main] org.apache.nifi.web.server.JettyServer Failed to start web server... shutting down.2021-08-29 04:36:48,799 WARN [main] org.apache.nifi.web.server.JettyServer Failed to start web server... shutting down.java.io.IOException: Function not implemented at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64) at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47) at org.apache.nifi.nar.NarAutoLoader.start(NarAutoLoader.java:68) at org.apache.nifi.web.server.JettyServer.start(JettyServer.java:1229) at org.apache.nifi.NiFi.<init>(NiFi.java:159) at org.apache.nifi.NiFi.<init>(NiFi.java:71) at org.apache.nifi.NiFi.main(NiFi.java:303)2021-08-29 04:36:48,830 INFO [Thread-1] org.apache.nifi.NiFi Initiating shutdown of Jetty web server...
```

**Comment by BenjaDiaz** [comment]
I managed to get this working by following this instructions:
https://issues.apache.org/jira/browse/NIFI-9177?focusedCommentId=17552621&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17552621

I also had to update Nifi version in the Dockerfile to 1.17.0
https://github.com/ging/fiware-draco/blob/master/nifi-ngsi-resources/docker/Dockerfile#L10
